[package]
name = "crabula_core"
version = "0.1.0"
edition = "2021"

[dependencies]
schemars = "1.0.0-alpha.3"
serde = "1.0.208"
serde_json = { version = "1.0.118", features = ["std"] }
thiserror = "1.0.63"
